"use server";

import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { TEXT_LIMITS, clip } from "@/lib/limits";
import { isConfirmed } from "@/lib/data/meals.types";
import type {
  MealDraft,
  MealResult,
  MealStatus,
  IntroductionCounts,
} from "@/lib/data/meals.types";

function revalidateApp() {
  revalidatePath("/", "layout");
}

/**
 * Rates a meal in one gesture ("loved it / mixed / refused"), without touching
 * foods or allergens — the quick-rating action of the "Aujourd'hui" screen (see
 * docs/ux-redesign.md §5). Tapping the active rating again clears it (the meal
 * goes back to unrated).
 *
 * Rating counts as **confirmation the meal happened**: it is the gesture the
 * parent already makes, they should not have to learn a second one. A refusal is
 * no exception — it confirms the meal like the other two, and changes nothing in
 * the programme (R5).
 */
export async function setMealResult(
  babyId: string,
  date: string,
  momentId: string,
  result: MealResult,
) {
  const supabase = await createClient();
  const { data: existing } = await supabase
    .from("meals")
    .select("id, status")
    .eq("baby_id", babyId)
    .eq("date", date)
    .eq("meal_moment_id", momentId)
    .maybeSingle();

  // The meal already exists (generated by the programme): just update the result.
  if (existing) {
    const current = existing.status as MealStatus;
    await supabase
      .from("meals")
      .update({
        result,
        // A rating sets the "servi" status, unless the parent had already said
        // more (composition replaced): we never downgrade a richer signal.
        //
        // Clearing the rating no longer puts the meal back on hold. Confirming
        // it happened and saying how it went are now two separate gestures
        // (`setMealServed`): erasing the second does not undo the first — the
        // meal was indeed eaten, we just no longer know whether it went down
        // well.
        status: result
          ? current === "remplace"
            ? "remplace"
            : "servi"
          : current,
        logged_at: new Date().toISOString(),
      })
      .eq("id", existing.id);
  } else if (result) {
    await supabase.from("meals").insert({
      baby_id: babyId,
      date,
      meal_moment_id: momentId,
      result,
      status: "servi",
      logged_at: new Date().toISOString(),
    });
  }
  revalidateApp();
}

/**
 * Persists a meal's whole state (a local edit committed in one go). Reconciles
 * foods / allergens / observations (full replacement). If everything is empty,
 * the meal is deleted.
 *
 * `draft.intent` says what the parent is doing, which drives the status and the
 * lock:
 *
 *   plan     — composing an upcoming meal → locked, stays "prévu"
 *   log      — reporting what happened → "servi" or "remplacé"
 *   evaluate — rating only, without touching the composition
 */
export async function saveMeal(
  babyId: string,
  date: string,
  momentId: string,
  draft: MealDraft,
) {
  const supabase = await createClient();
  const intent = draft.intent ?? "plan";

  const isEmpty =
    !draft.result &&
    !draft.note.trim() &&
    draft.foodIds.length === 0 &&
    draft.allergenIds.length === 0 &&
    draft.observations.length === 0;

  const { data: existing } = await supabase
    .from("meals")
    .select("id, status, locked, planned_food_ids, meal_items(food_id)")
    .eq("baby_id", babyId)
    .eq("date", date)
    .eq("meal_moment_id", momentId)
    .maybeSingle();

  if (isEmpty) {
    if (existing) await supabase.from("meals").delete().eq("id", existing.id);
    revalidateApp();
    return;
  }

  // Original composition: what the programme had written. Recorded on the first
  // correction only — after that it stays put, or the second correction would
  // erase the trace of the first.
  const previousIds = ((existing?.meal_items ?? []) as { food_id: string }[])
    .map((it) => it.food_id)
    .sort();
  const plannedIds: string[] =
    (existing?.planned_food_ids as string[] | null) ?? previousIds;
  const sameAsPlanned =
    plannedIds.length === draft.foodIds.length &&
    [...draft.foodIds].sort().every((id, i) => id === plannedIds[i]);

  const currentStatus = (existing?.status ?? "prevu") as MealStatus;
  const status: MealStatus =
    intent === "plan"
      ? currentStatus
      : intent === "log"
        ? sameAsPlanned
          ? "servi"
          : "remplace"
        : // evaluate: the rating confirms, without downgrading a richer signal
          draft.result
          ? currentStatus === "remplace"
            ? "remplace"
            : "servi"
          : currentStatus === "servi"
            ? "prevu"
            : currentStatus;

  const stateColumns = {
    status,
    // The parent has had their hands in this meal: the engine will not rewrite it.
    locked: intent === "evaluate" ? (existing?.locked ?? false) : true,
    logged_at:
      intent === "evaluate" && !draft.result ? null : new Date().toISOString(),
    planned_food_ids: existing?.planned_food_ids ?? plannedIds,
  };

  let mealId = existing?.id as string | undefined;
  if (!mealId) {
    const { data: created, error } = await supabase
      .from("meals")
      .insert({
        baby_id: babyId,
        date,
        meal_moment_id: momentId,
        result: draft.result,
        note: clip(draft.note.trim(), TEXT_LIMITS.mealNote) || null,
        ...stateColumns,
        // Nothing was planned: there is no original plan to keep.
        planned_food_ids: null,
      })
      .select("id")
      .single();
    if (error || !created) return;
    mealId = created.id as string;
  } else {
    await supabase
      .from("meals")
      .update({
        result: draft.result,
        note: clip(draft.note.trim(), TEXT_LIMITS.mealNote) || null,
        ...stateColumns,
      })
      .eq("id", mealId);
  }

  // Doses and provenance of the kept foods: rewriting them flat would lose the
  // allergen protocol doses ("une pointe de cuillère"), which cannot be
  // recomputed.
  const { data: priorItems } = await supabase
    .from("meal_items")
    .select("food_id, dose, source, skipped")
    .eq("meal_id", mealId);
  const priorById = new Map(
    (
      (priorItems ?? []) as {
        food_id: string;
        dose: string | null;
        source: string;
        skipped: boolean;
      }[]
    ).map((it) => [it.food_id, it]),
  );

  // Full replacement of the linked rows
  await supabase.from("meal_items").delete().eq("meal_id", mealId);
  await supabase.from("meal_allergens").delete().eq("meal_id", mealId);
  await supabase.from("intake_observations").delete().eq("meal_id", mealId);

  if (draft.foodIds.length) {
    await supabase.from("meal_items").insert(
      draft.foodIds.map((food_id) => {
        const prior = priorById.get(food_id);
        return {
          meal_id: mealId,
          food_id,
          dose: prior?.dose ?? null,
          source: prior?.source ?? "parent",
          skipped: prior?.skipped ?? false,
        };
      }),
    );
  }
  if (draft.allergenIds.length) {
    await supabase.from("meal_allergens").insert(
      draft.allergenIds.map((allergen_id) => ({
        meal_id: mealId,
        allergen_id,
      })),
    );
  }
  if (draft.observations.length) {
    await supabase.from("intake_observations").insert(
      draft.observations.map((o) => ({
        meal_id: mealId,
        effect_type: o.effect_type,
        severity: o.severity,
        note: clip(o.note.trim(), TEXT_LIMITS.observationNote) || null,
      })),
    );
  }

  revalidateApp();
}

/**
 * Number of introductions per food / allergen from the start of the calendar up
 * to and including `dateISO` (for the optional display in the editor).
 */
export async function getIntroductionCounts(
  babyId: string,
  dateISO: string,
): Promise<IntroductionCounts> {
  const supabase = await createClient();
  const { data } = await supabase
    .from("meals")
    .select(
      "date, status, meal_items(food_id, skipped), meal_allergens(allergen_id)",
    )
    .eq("baby_id", babyId)
    .neq("status", "saute")
    .lte("date", dateISO);

  const foods: Record<string, number> = {};
  const allergens: Record<string, number> = {};
  for (const m of (data ?? []) as {
    status: MealStatus;
    meal_items: { food_id: string; skipped: boolean }[];
    meal_allergens: { allergen_id: string }[];
  }[]) {
    for (const it of m.meal_items ?? []) {
      if (it.skipped) continue;
      foods[it.food_id] = (foods[it.food_id] ?? 0) + 1;
    }
    // Allergens only count on a confirmed meal: believing the child exposed
    // when they were not would be the product's one dangerous lie (trust
    // asymmetry, docs/feats §3).
    if (!isConfirmed(m)) continue;
    for (const a of m.meal_allergens ?? [])
      allergens[a.allergen_id] = (allergens[a.allergen_id] ?? 0) + 1;
  }
  return { foods, allergens };
}
